apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-{{ .Values.version }}
  labels:
    app: api
    version: {{ .Values.version | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: api
      version: {{ .Values.version | quote }}
  template:
    metadata:
      labels:
        app: api
        version: {{ .Values.version | quote }}
    spec:
      containers:
        - name: http-echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-text=VERSION={{ .Values.version }}"
            - "-listen=:5678"
          ports:
            - name: http
              containerPort: 5678
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
